# Generated by Django 5.2.8 on 2025-11-20 03:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='salary_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='payroll.payrollupload'),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='payroll.employee'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='upload',
        ),
    ]
