# Generated by Django 5.2.8 on 2025-11-20 03:05

from django.db import migrations
from django.utils import timezone


def migrate_salary_data(apps, schema_editor):
    """
    Migrate existing salary component data to new structure.
    Link salary components to their uploads and set salary_month.
    """
    SalaryComponent = apps.get_model('payroll', 'SalaryComponent')
    Employee = apps.get_model('payroll', 'Employee')
    PayrollUpload = apps.get_model('payroll', 'PayrollUpload')
    
    # For each salary component without upload, try to find the appropriate upload
    # Since we don't have direct link, we'll use a heuristic approach
    uploads = list(PayrollUpload.objects.all().order_by('upload_date'))
    
    for salary in SalaryComponent.objects.filter(upload__isnull=True):
        # Find the first upload (or create a default one)
        if uploads:
            # Assign to the first upload for now
            salary.upload = uploads[0]
            salary.salary_month = uploads[0].upload_date.date()
        else:
            # Create a default upload if none exists
            from django.contrib.auth.models import User
            default_user = User.objects.first()
            if not default_user:
                continue
            
            default_upload = PayrollUpload.objects.create(
                user=default_user,
                filename='migrated_data.xlsx',
                status='completed'
            )
            salary.upload = default_upload
            salary.salary_month = default_upload.upload_date.date()
        
        salary.save()


def reverse_migrate_salary_data(apps, schema_editor):
    """Reverse migration - not needed for this case"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_step1_restructure_models'),
    ]

    operations = [
        migrations.RunPython(migrate_salary_data, reverse_migrate_salary_data),
    ]
