# Generated by Django 5.2.8 on 2025-11-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_step4_merge_duplicate_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='salarycomponent',
            unique_together={('employee', 'upload', 'salary_month')},
        ),
    ]
