# Generated by Django 5.2.8 on 2025-11-20 03:13

from django.db import migrations
from django.db.models import Count


def merge_duplicate_employees(apps, schema_editor):
    """
    Merge duplicate employees and reassign their salary records.
    Keep the first employee record and delete duplicates.
    """
    Employee = apps.get_model('payroll', 'Employee')
    SalaryComponent = apps.get_model('payroll', 'SalaryComponent')
    
    # Find all duplicate employee_ids
    duplicates = Employee.objects.values('employee_id').annotate(
        count=Count('employee_id')
    ).filter(count__gt=1)
    
    for duplicate in duplicates:
        employee_id = duplicate['employee_id']
        
        # Get all employee records with this employee_id
        employees = Employee.objects.filter(employee_id=employee_id).order_by('id')
        
        if employees.count() <= 1:
            continue
            
        # Keep the first employee record
        primary_employee = employees.first()
        duplicate_employees = employees[1:]
        
        # Reassign all salary components from duplicates to primary employee
        for dup_employee in duplicate_employees:
            SalaryComponent.objects.filter(employee=dup_employee).update(
                employee=primary_employee
            )
            
        # Delete duplicate employee records
        Employee.objects.filter(
            employee_id=employee_id
        ).exclude(id=primary_employee.id).delete()


def reverse_merge_duplicate_employees(apps, schema_editor):
    """Reverse operation - not needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_step2_migrate_data'),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_employees, reverse_merge_duplicate_employees),
    ]
