# Generated by Django 4.2.7
# Step 1: Add user field as nullable

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0005_userprofile'),
    ]

    operations = [
        # Add user field as nullable first
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(
                null=True, 
                blank=True,
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='employees', 
                to=settings.AUTH_USER_MODEL
            ),
        ),
        
        # Remove unique constraint on employee_id  
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=50),
        ),
    ]
