# Generated by Django 4.2.7
# Step 2: Populate user field for existing employees

from django.db import migrations


def populate_employee_users(apps, schema_editor):
    """
    Populate user field for existing employees based on their salary components
    """
    Employee = apps.get_model('payroll', 'Employee')
    SalaryComponent = apps.get_model('payroll', 'SalaryComponent')
    User = apps.get_model('auth', 'User')  # Get User model from apps
    
    for employee in Employee.objects.filter(user__isnull=True):
        # Find the first salary component for this employee to determine the user
        salary = SalaryComponent.objects.filter(employee=employee).first()
        if salary and salary.upload:
            employee.user = salary.upload.user
            employee.save()
        else:
            # If no salary component found, assign to the first available user
            # or delete the employee if no users exist
            first_user = User.objects.first()
            if first_user:
                employee.user = first_user
                employee.save()
            else:
                employee.delete()


def reverse_populate_employee_users(apps, schema_editor):
    """Reverse operation - set user field to null"""
    Employee = apps.get_model('payroll', 'Employee')
    Employee.objects.all().update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_add_user_field_nullable'),
    ]

    operations = [
        migrations.RunPython(
            populate_employee_users,
            reverse_populate_employee_users,
        ),
    ]
