# Generated by Django 4.2.7 
# Step 3: Make user field non-nullable and add unique constraint

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0007_populate_user_field'),
    ]

    operations = [
        # Make user field non-nullable
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='employees', 
                to=settings.AUTH_USER_MODEL
            ),
        ),
        
        # Add unique constraint for (user, employee_id)
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('user', 'employee_id')},
        ),
    ]
