# Generated by Django 5.2.8 on 2025-11-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_populate_employee_users'),
        ('payroll', '0008_make_user_field_required'),
    ]

    operations = [
    ]
